### ISSUE TITLE
Details of environmental dependence.

### ISSUE THREAD

**Issue by caffecoffee** [TomHeaven/msba_reid#1]
Hello Dr Tan! I am trying to using the repo, but i don't know the dependency such as the version of pytorch.

**Comment by TomHeaven** [comment]
A quick answer is pytorch 1.3.1, cv2 and so on. When you run the script, the terminal output will tell you which python packages are missing.  

I will add a requirement.txt file later.

**Comment by caffecoffee** [comment]
Thanks! 

I'm wondering how about the performance of **msba_reid** in **NAIC**?

**Comment by TomHeaven** [comment]
We got 11th place in the first round, and 30th place in the second round. However, the code & tricks used in NAIC are not totally  the same with`msba_reid`. Especially in the second round, iterative fine tune on the huge test dataset greatly affects the ReID score.

**Comment by caffecoffee** [comment]
Thanks a lot for your kind reply!

**Comment by TomHeaven** [comment]
A requirements.txt file has been added.
