### ISSUE TITLE
keyError:'state_dict'

### ISSUE THREAD

**Issue by Weiziwei521** [TomHeaven/msba_reid#2]
When I try to run according to readme,after configuring the environment in the requirement， download the data and pre-trained model and modify the file directory, and then run the sh script file, a keyerror appears，but when checking the parameters of the pre-trained model, it is loaded into it. What is wrong? Looking forward to your reply,thanks.

Traceback (most recent call last):
  File "tools/train.py", line 70, in <module>
    main()
  File "tools/train.py", line 65, in main
    reid_system = ReidSystem(cfg, logger, writer)
  File "./engine/trainer.py", line 33, in __init__
    self.model = build_model(cfg, self.num_classes)
  File "./modeling/__init__.py", line 32, in build_model
    cfg.MODEL.PRETRAIN_PATH)
  File "./modeling/baseline_parts.py", line 37, in __init__
    self.base.load_pretrain(model_path)
  File "./modeling/backbones/resnet.py", line 166, in load_pretrain
    state_dict = torch.load(model_path)['state_dict']
KeyError: 'state_dict'

**Comment by TomHeaven** [comment]
There is a small problem in the training script. You need to change the parameter 'MODEL.PRETRAIN_PATH' to your custom location such as
```shell
...
# MODEL.PRETRAIN_PATH '/home/tomheaven/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar' \
MODEL.PRETRAIN_PATH '~/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar' \
```

If the relative path is not working, try an absolute path.

I'll fix this in the next commit.

**Comment by Weiziwei521** [comment]
我把下载好的预训练模型resnet50_ibn_a放入到了我自己的文件夹下（'/media/speech/7672/daima/msba_reid_paper/modeling/resnet50_ibn_a.pth'），并且在config/defaults.py中修改MODEL.PRETRAIN_PATH为上述路径，还是会出现上述错误。

**Comment by TomHeaven** [comment]
可能是你下的模型权重文件损坏了？我尝试了以下手动加载这个resnet50_ibn_a.pth.tar，可以看到sd的keys()里是有'state_dict'的。

```
Python 3.6.10 (default, Feb 24 2020, 16:57:07) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> path = '/home/tomheaven/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar'
>>> sd = torch.load(path)
>>> sd.keys()
dict_keys(['state_dict'])

```

如果你的keys()没有state_dict，可能是ibn的作者更新了权重。只需要把报错处的`['state_dict']`删掉就可以了，如下：
```
state_dict = torch.load(model_path)
```

我已将我所用的resnet50_ibn_a.pth.tar传到[百度网盘](https://pan.baidu.com/s/1scchUfCX5rUBausHX4FqBA)，提取码:gizs

**Comment by Weiziwei521** [comment]
按照上边您说的方法，我的sd的keys也是有值的。之后我把报错处的['state_dict']删掉之后，会出现KeyError: 'module.fc.weight'。重新下载您百度网盘的resnet50_ibn_a之后，开始正常训练了。谢谢~

**Comment by chenxiangzZ** [comment]
你好，我也遇到了这样的问题，请问百度网盘的提取码多少呢

**Comment by TomHeaven** [comment]
> 你好，我也遇到了这样的问题，请问百度网盘的提取码多少呢

Readme里有，提取码:gizs。
