### ISSUE TITLE
请问如何改成两个gpu下的训练？

### ISSUE THREAD

**Issue by GJTNB** [TomHeaven/msba_reid#4]

**Comment by GJTNB** [comment]
是不是只需要修改脚本文件上的gpu就可以了

**Comment by GJTNB** [comment]
还有请问你的硬件配置是多少，我在两块k80 11g上面跑，总是会突然卡死

**Comment by GJTNB** [comment]
我只修改了脚本文件上得gpu,改为了GPUS='0,1'，但是这样设置后训练在第一个batch就卡死了，只选择一块gpu的话，大概会跑3个epoch然后卡死。请问可以怎么解决

**Comment by GJTNB** [comment]
还有请问你的黄金pytorch、cuda版本是啥，我训练大概4个epoch就会报下面错误，我是按照你给的requirement.txt安装的环境 File "tools/train.py", line 57, in main
    reid_system.train()
  File "./engine/trainer.py", line 226, in train
    self.training_step(batch)
  File "./engine/trainer.py", line 145, in training_step
    self.opt.step()
  File "/home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/optim/adam.py", line 101, in step
    denom = exp_avg_sq.sqrt().add_(group['eps'])
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMathPointwise.cu:50
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /opt/conda/conda-bld/pytorch_1556653099582/work/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7ff9dd679dc5 in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14792 (0x7ff9dcfec792 in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x50 (0x7ff9dd669640 in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x3067fb (0x7ff89fd6b7fb in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x13ff1b (0x7ff9dd9d2f1b in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x3bf384 (0x7ff9ddc52384 in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3bf3d1 (0x7ff9ddc523d1 in /home/lab419/anaconda2/envs/mudeep/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #19: __libc_start_main + 0xe7 (0x7ff9e1bc9b97 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by TomHeaven** [comment]
你这种情况很有可能是显存不足引发的，这份代码在Nvidia GTX 1080Ti，Titan V或者2080Ti上是可以直接运行的。如果设备显存太小，把batch size调小再试试。

另外检查一下Nvidia驱动版本是否与CUDA版本匹配，可以尝试更新一下Nvidia驱动。最好是用CUDA SDK带的驱动版本，这样可以确保没问题。

关于软件版本，Python3.6，Pytorch 1.3.1/1.6，CUDA 10/10.1我都跑过。

**Comment by GJTNB** [comment]
谢谢回复，我发现可能是我们的服务器的问题，我租了个服务器1080ti的就可以了，还有一个问题请问下，三元组采样的P和K是怎么设置的，是不是IMS_PER_BATCH=64，NUM_INSTANCE=4 其中的NUM_INSTANCE代表K，P就是64/4=16

**Comment by TomHeaven** [comment]
是这样的。NUM_INSTANCE就是ReID论文中所说的K，设置为4是一个较优的默认值。如果数据集存在很多样本数小于4的行人，也可以考虑减小这个值。这需要尝试。P的值不值那么关键，主要是看显存能容纳的BatchSize是多少，间接得到P的值。

**Comment by GJTNB** [comment]
非常感谢
