### ISSUE TITLE
Bug in /modeling/baseline_parts_ft.py

### ISSUE THREAD

**Issue by limengzhu3211** [TomHeaven/msba_reid#5]
You may have a typo here. 
las000000t_stride -> last_stride

https://github.com/TomHeaven/msba_reid/blob/44feac1e2f7e0c619a9b75ef19250ae7454be65e/modeling/baseline_parts_ft.py#L29-L30

**Comment by TomHeaven** [comment]
Thanks for the remind. This may be caused by unexpected touch of my keyboard, which is embarrassing...

**Comment by TomHeaven** [comment]
It has been fixed.
