### ISSUE TITLE
test on cuhk03

### ISSUE THREAD

**Issue by Mr-Da-Yang** [TomHeaven/msba_reid#6]
Hello author, first of all thank you for your outstanding contribution!
We found that you use strongbaseline (Luo) as the baseline. When measuring cuhk03, you used a separate measurement method.
 I put your cuhk03 measurement method in the baseline and found that map is greater than rank1, but in your paper, the map is smaller than rank1. 
I would like to ask why, what parameters need to be adjusted on the baseline?
Look forward to your reply！！！

**Comment by TomHeaven** [comment]
In fact, the repo is inherited from Liao Xingyu's ReID repo including the evaluation modules. R1 is a more relax than mAP and should not be smaller than mAP.

Are you sure you have completely ported our model definitions with pre-trained weights to Luo's baseline? If so, maybe you should pay attention to the data loading part.

**Comment by Mr-Da-Yang** [comment]
Hello, I am also studying this article of yours recently（MSBA: Multiple Scales, Branches and Attention
Network With Bag of Tricks for Person
Re-Identification）. Add your cuhk03 measurement method to strongbaseline, and keep the others unchanged, the result is still map&gt;rank1



May I ask whether you used the market1501 measurement method or the cuhk03 measurement method when doing the cuhk03 experiment. The students in my laboratory also encountered the above problems. I look forward to your guidance, thank you!thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 中午12:01
收件人: ***@***.***&gt;; 
抄送: "Get ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TomHeaven/msba_reid] test on cuhk03 (#6)





 
In fact, the repo is inherited from Liao Xingyu's ReID repo including the evaluation modules. R1 is a more relax than mAP and should not be smaller than mAP.
 
Are you sure you have completely ported our model definitions with pre-trained weights to Luo's baseline? If so, maybe you should pay attention to the data loading part.

**Comment by TomHeaven** [comment]
Note reranking will change R1 and mAP. If you use reranking on CUHK03 dataset, it is possible to get results such as `mAP > R1`.
