### ISSUE TITLE
run demo.py

### ISSUE THREAD

**Issue by Jacobxz** [TomHeaven/msba_reid#7]
Hi, this is a really nice project!but i have a trouble

(bcf) XX@server:/home/XX/msba$ python demo.py
1
Traceback (most recent call last):
  File "demo.py", line 120, in <module>
    reid = Reid()
  File "demo.py", line 51, in __init__
    self.model = torch.jit.load('/home/XX/msba/model_best.pth')
  File "/home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/jit/__init__.py", line 235, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: [enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading zip archive: failed finding central directory
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b (0x7f88edabf3bb in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x72 (0x7f889e7eafa2 in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::init() + 0xa1 (0x7f889e7edf71 in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f889e7f1044 in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: torch::jit::import_ir_module(std::shared_ptr<torch::jit::script::CompilationUnit>, std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x35 (0x7f889fb50c85 in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x7855c5 (0x7f88f10d25c5 in /home/XX/anaconda3/envs/bcf/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x28c076 (0x7f88f0bd9076 in /home/XX/anaconda3/envs/bcf/lib/python3.6

Anyone knows how to fix it?

**Comment by TomHeaven** [comment]
You check out the wrong branch. The master branch is for a competition, which is deprecated now. Check out the paper branch here: https://github.com/TomHeaven/msba_reid/tree/paper.
